### ISSUE TITLE
Save dark mode setting

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [simple-login/website#5]
Hi every time i login into my account i have to switch the theme to dark mode. I would be nice if this setting is saved.

**Comment by nguyenkims** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc that's due to the fact that the theme preference is stored in the browser cookie that gets cleared when you log out.

We have a ticket in the roadmap https://trello.com/c/Mlhrnz6B/148-automatically-match-system-theme-dark-light that allow to automatically match the system theme, that could be useful :). Feel free to upvote it to make it happen sooner.
